name: Go Test

on: [push]

env:
  GO111MODULE: on

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Install go-cli-template
      run: go get github.com/dreadatour/go-cli-template@5a0e7bdae4be76b88d9f30f4e849f6915f0b4ed0
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Replace github user & project
      run: $(go env GOPATH)/bin/go-cli-template --GithubUser sensu-community --GithubProject handler-plugin-template > go.mod
    - name: Test
      run: go test -v ./...
